services:
    nockchain:
        image: herokatodev/nockchain:latest
        environment:
            - WALLET=2tPBzPrfgV8AUoz4qzoCqSUBX2HkybXuLqHcs8s4X1x7tCAT6BhAPRtwUhETrp6C8rq1UbsjhTg34abXfWFZWG4AYsYovBGqhD4QyvWh4SwPdujLSsK6fdoJrd5Ytv8hH4wx
            - CHAIN_CODE=2FWgPtUcydJ7TK1awz36sdFK4oPqwutGU3cKpnKMhARy
            - PEERS_LIST=62.171.131.52
        tty: true
        stdin_open: true
        restart: always
        network_mode: host
        # deploy:
        #   replicas: 1
